/**
 * UpdatedLeadDataDTO_Helper.java
 *
 * This file was auto-generated from WSDL
 * by the IBM Web services WSDL2Java emitter.
 * gm1318.02 v5913144247
 */

package com.ibm.lms.dto.webservice;

public class UpdatedLeadDataDTO_Helper {
    // Type metadata
    private static final com.ibm.ws.webservices.engine.description.TypeDesc typeDesc =
        new com.ibm.ws.webservices.engine.description.TypeDesc(UpdatedLeadDataDTO.class);

    static {
        typeDesc.setOption("buildNum","gm1318.02");
        com.ibm.ws.webservices.engine.description.FieldDesc field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("prospectsName");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "prospectsName"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("prospectsMobileNumber");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "prospectsMobileNumber"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("alternateContactNumber");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "alternateContactNumber"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("landlineNumber");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "landlineNumber"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("address");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "address"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("address2");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "address2"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("city");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "city"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("pincode");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "pincode"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("state");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "state"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("circle");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "circle"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("maritalStatus");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "maritalStatus"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("requestCategory");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "requestCategory"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("appointmentTime");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "appointmentTime"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("email");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "email"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("primaryLanguage");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "primaryLanguage"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("subZone");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "subZone"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("zone");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "zone"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("remarks");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "remarks"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("qualLeadParam");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "qualLeadParam"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("service");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "service"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("tag");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "tag"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("isCustomer");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "isCustomer"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("adParameter");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "adParameter"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("utmLAbels");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "utmLAbels"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("company");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "company"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("cityZoneCode");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "cityZoneCode"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("plan");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "plan"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("rental");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "rental"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("allocatedNo");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "allocatedNo"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("onlineCafNo");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "onlineCafNo"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("pytAmt");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "pytAmt"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("tranRefno");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "tranRefno"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("agencyId");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "agencyId"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("udId");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "udId"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("cityId");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "cityId"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("circleId");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "circleId"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("feasibilityparam");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "feasibilityparam"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("planId");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "planId"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("customerInfoId");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "customerInfoId"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("rentaltype");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "rentaltype"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("freebiecount");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "freebiecount"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("boostercount");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "boostercount"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("freebietaken");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "freebietaken"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("boostertaken");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "boostertaken"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("flag");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "flag"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("prepaidnumber");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "prepaidnumber"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("offer");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "offer"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("downloadlimit");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "downloadlimit"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("devicemrp");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "devicemrp"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("voicebenefit");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "voicebenefit"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("dataquota");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "dataquota"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("usertype");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "usertype"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("devicetaken");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "devicetaken"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("benefit");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "benefit"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("pkgduration");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "pkgduration"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("hlrno");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "hlrno"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("rsuCode");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "rsuCode"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("dob");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "dob"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("trxnId");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "trxnId"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("leadId");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "leadId"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("status");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "status"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("subStatus");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "subStatus"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("cafNumber");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "cafNumber"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("productBought");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "productBought"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("rentalPlan");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "rentalPlan"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("paymentCollected");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "paymentCollected"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("paymentType");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "paymentType"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("paymentAmount");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "paymentAmount"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("competitorChosen");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "competitorChosen"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("sentBy");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "sentBy"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("latitude");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "latitude"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("longitude");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "longitude"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("assignedRemarks");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "assignedRemarks"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("paymentStatus");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "paymentStatus"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("taskStartTime");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "taskStartTime"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("taskEndTime");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "taskEndTime"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("paymentAmtDue");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "paymentAmtDue"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("appointmentEndTime");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "appointmentEndTime"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam1");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam1"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam2");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam2"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam3");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam3"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam4");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam4"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam5");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam5"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam6");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam6"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam7");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam7"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam8");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam8"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam9");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam9"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("extraParam10");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "extraParam10"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
        field = new com.ibm.ws.webservices.engine.description.ElementDesc();
        field.setFieldName("productLob");
        field.setXmlName(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://webservice.dto.lms.ibm.com", "productLob"));
        field.setXmlType(com.ibm.ws.webservices.engine.utils.QNameTable.createQName("http://www.w3.org/2001/XMLSchema", "string"));
        typeDesc.addFieldDesc(field);
    };

    /**
     * Return type metadata object
     */
    public static com.ibm.ws.webservices.engine.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static com.ibm.ws.webservices.engine.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class javaType,  
           javax.xml.namespace.QName xmlType) {
        return 
          new UpdatedLeadDataDTO_Ser(
            javaType, xmlType, typeDesc);
    };

    /**
     * Get Custom Deserializer
     */
    public static com.ibm.ws.webservices.engine.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class javaType,  
           javax.xml.namespace.QName xmlType) {
        return 
          new UpdatedLeadDataDTO_Deser(
            javaType, xmlType, typeDesc);
    };

}
