//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.lms.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "createLeadData", namespace = "http://webservice.lms.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createLeadData", namespace = "http://webservice.lms.ibm.com/", propOrder = {
    "arg0",
    "arg1"
})
public class CreateLeadData {

    @XmlElement(name = "arg0", namespace = "")
    private com.ibm.lms.dto.AuthorizationData arg0;
    @XmlElement(name = "arg1", namespace = "", nillable = true)
    private com.ibm.lms.engine.dataobjects.CreateLeadDO_Ver1 [] arg1;

    /**
     * 
     * @return
     *     returns AuthorizationData
     */
    public com.ibm.lms.dto.AuthorizationData getArg0() {
        return this.arg0;
    }

    /**
     * 
     * @param arg0
     *     the value for the arg0 property
     */
    public void setArg0(com.ibm.lms.dto.AuthorizationData arg0) {
        this.arg0 = arg0;
    }

    /**
     * 
     * @return
     *     returns CreateLeadDO_Ver1[]
     */
    public com.ibm.lms.engine.dataobjects.CreateLeadDO_Ver1 [] getArg1() {
        return this.arg1;
    }

    /**
     * 
     * @param arg1
     *     the value for the arg1 property
     */
    public void setArg1(com.ibm.lms.engine.dataobjects.CreateLeadDO_Ver1 [] arg1) {
        this.arg1 = arg1;
    }

}
